#!C:\Users\saina\Desktop\DS_ML_AI\Scaler\Projects_or_Case_Studies_GIT\Network_Anomaly_Detection_Project\nadp_venv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
